### PR TITLE
Super important changes

### PR DESCRIPTION
**Pull request by cameronus**
plz

### CODE REVIEW

**Comment by johnny-y-wang** [comment]
This PR puts a PSA on the bell schedule page for the upcoming CTF event. Would really appreciate a shoutout :)

**Review by johnny-y-wang — APPROVED** [review]

**Comment by neilramaswamy** [comment]
Please include a screenshot of your changes in your PR.

_This was an automatic action performed by the Harker Dev Bellschedule CI/CD bot._

**Review by johnny-y-wang — APPROVED** [review]
lgtm

**Comment by neilramaswamy** [comment]
Mr. Wang, are you trying to impersonate a Harker Dev member with your comment "lgtm?"

**Comment by cameronus** [comment]
Excuse me, Mr. Wang and I are honorable HarkerDev™®© members like yourself

**Comment by bokken12** [comment]
Sorry, but our policy is not to advertise for other groups on campus, we don't want to set a precedent that everyone can and should do it.

**Comment by nakulbajaj** [comment]
I believe that the general Harker School community would appreciate this change, actually

**Comment by bokken12** [comment]
I don't mean to say that they would not. I believe that HarkerCTF is a great event, and I've enjoyed attending it in the past. At the same time, I do not wish to become the arbiter of which events would or would not be appreciated and so would encourage that it go through more traditional methods of spreading the word.

**Pull request closed without merging**
