### PR TITLE
Font Design Changes and Easier Sharing

### PR DESCRIPTION
**Pull request by nakulbajaj**
Added fonts for body and headers
-"Trends" font using Cufon in header
-"Raleway" font using google fonts

### CODE REVIEW

**Comment by nakulbajaj** [comment]
Finally done with squashing commits! 😅

**Comment by Andrew-Tierno** [comment]
Hey Nakul, I'm not super sold on the new font, particularly how the numbers align below the letters as shown here: 
screen shot 2016-08-28 at 9 41 31 pm
It seems too much like written text, which goes against the clean aesthetic we're aiming for. However, thank you for the suggestion, I'd love to hear more from you!

**Comment by mananshah99** [comment]
I'm fine with the mailto: href, @Andrew-Tierno if you're cool with that @nakulbajaj can make a new PR with that addition? I agree with you on the font, though, I like the clean look as it is.

**Comment by nakulbajaj** [comment]
Thanks for the feedback!

Let me know whether I should create a new PR with mailto.

**Pull request closed without merging**
